### ISSUE TITLE
[GSSC-PreTVT]English string occurs when input lb oracle in command line in JPN locale

### ISSUE THREAD

**Issue by gongkegongke** [strongloop/generator-loopback#376]
Test Case: 11.020.310

![image](https://user-images.githubusercontent.com/34856053/44082571-359fe720-9fe4-11e8-8378-a64b36aba31c.png)

Issue: English string occurs when input **lb oracle** in command line

**Comment by dhmlau** [comment]
It's fixed in this commit https://github.com/strongloop/generator-loopback/commit/f3c359ab4808399595dac108af6eed2a49c0ff32.  I just released generator-loopback@5.9.0 which contains the fix. 
Please pick up the latest version of `generator-loopback` and try again. Thanks.

**Comment by candytangnb** [comment]
@dhmlau I download the latest master build 2076 today from https://na.artifactory.swg-devops.com/artifactory/webapp/#/builds/velox-toolkit-master/2076/1534369183514/velox-toolkit-master. But still see English strings.
<img width="1059" alt="image" src="https://media.github.ibm.com/user/17224/files/75f5eb64-a13b-11e8-9b3d-d30d9a6f6a33">

**Comment by dhmlau** [comment]
PR https://github.com/strongloop/generator-loopback/pull/379.

@candytangnb , sorry that I didn't extract the messages properly last time, so this line is not correct: https://github.com/strongloop/generator-loopback/blob/master/intl/en/messages.json#L222.

Would like to see your thoughts on getting it changed in the translated version.  Supposedly, I just need to add `{0}` in the corresponding message in each of the language file.  But I know that you'd prefer us not to touch the translated files because we might mess up with the encoding.  Please let me know your thoughts.  Thanks.

**Comment by candytangnb** [comment]
To keep translation consitent between DEV and translators, we would suggest DEV do not update translation files by yourself. We will add an emergency drop for pretvt issues. Specific time will be updated in mail later.

**Comment by dhmlau** [comment]
ok thanks. It looks like we have some other changes in the message file too.

**Comment by dhmlau** [comment]
PR #379 is merged.  Next step is to get the messages.json translated.

**Comment by dhmlau** [comment]
Paused by translation.  Next translation drop is Aug 21.

**Comment by dhmlau** [comment]
Translation for ja/zh/ko are in.  Released in `generator-loopback@5.9.1`

**Comment by dhmlau** [comment]
All the translation files have been released.  Closing this ticket as resolved.

**Comment by candytangnb** [comment]
verified and fixed
<img width="588" alt="image" src="https://user-images.githubusercontent.com/26452457/45342393-69f09680-b5d0-11e8-921c-1c7e46e5d95f.png">
